#!/bin/bash
set -e

if [ -z "$1" ]; then
  prs=$(gh pr view --jq '.[].number' --json number)
  echo "Updating current PR"
elif [ $1 == "--mine" ]; then
  prs=$(gh pr list --author @me --jq '.[].number' --json number)
  echo "Updating all your PRs"
else
  prs=($1)
  echo "Updating specified PR"
fi

for pr in ${prs[@]}; do
  read -r number sha < <(gh pr view $pr --json number,commits --jq '[.number,.commits[-1].oid]|@tsv')
  echo "Updating PR #${number}"

  gh api --silent "repos/{owner}/{repo}/pulls/${number}/update-branch" \
    --field expected_head_sha=${sha} \
    --method PUT
done
