#!/bin/bash
set -e

read -r number sha < <(gh pr view ${1} --json number,commits --jq '[.number,.commits[-1].oid]|@tsv')

exec gh api --silent "repos/{owner}/{repo}/pulls/${number}/update-branch" \
  --field expected_head_sha=${sha} \
  --method PUT
